name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
#    - name: Add package source
#      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/microsoft/index.json"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
#    - name: Publish
#      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
#      run: dotnet nuget push **/bin/Release/Furly.*.nupkg --source "github" --skip-duplicate
#    - name: Remove package source
#      run: dotnet nuget remove source github
    - name: Publish to Myget
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: dotnet nuget push **/bin/Release/Furly.*.nupkg -k $MYGET_API_KEY -s https://www.myget.org/F/furlypublic/api/v3/index.json --skip-duplicate
      env:
        MYGET_API_KEY: ${{ secrets.MYGET_API_KEY }}
